{{- if not .Values.secrets.useSecretName -}}
apiVersion: v1
kind: Secret
metadata:
  name: secrets-{{ include "go-api.fullname" . }}
  labels:
    app: secrets-data-{{ include "go-api.fullname" . }}
    chart: {{ include "go-api.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
stringData:
  username: "{{ .Values.dbinfo.username }}"
  password: "{{ .Values.dbinfo.password }}"
{{- end }}
